server:
  port: 3000
spring:
  application:
    name: URL-Shortner
  datasource:
    url: jdbc:postgresql://ep-broad-base-aoa76d0h-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_dCAN6wBkJ3SV

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 4c59b65c7bc7ef0fdc6f902b35317e2cb3e9b353db6aebdf72df9c1d7160cfa0
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
cookie:
  secure: false
  same-site: Lax

logging:
  level:
    org:
      springframework:
        security: "TRACE"
