server:
  port: ${PORT:8080}
spring:
  application:
    name: URL-Shortner
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET:4c59b65c7bc7ef0fdc6f902b35317e2cb3e9b353db6aebdf72df9c1d7160cfa0}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

cookie:
  secure: ${COOKIE_SECURE:false}
  same-site: ${COOKIE_SAME_SITE:Lax}

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL_SECURITY:TRACE}